SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
SET NAMES utf8mb4;

CREATE TABLE `scuole` (`id` int(11) NOT NULL AUTO_INCREMENT, `nome` enum('ITIS','LICEO') NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `indirizzi` (`id` int(11) NOT NULL AUTO_INCREMENT, `nome` varchar(100) NOT NULL, `id_scuola` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `id_scuola` (`id_scuola`), CONSTRAINT `indirizzi_ibfk_1` FOREIGN KEY (`id_scuola`) REFERENCES `scuole` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `materie` (`id` int(11) NOT NULL AUTO_INCREMENT, `nome` varchar(100) NOT NULL, `id_indirizzo` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `id_indirizzo` (`id_indirizzo`), CONSTRAINT `materie_ibfk_1` FOREIGN KEY (`id_indirizzo`) REFERENCES `indirizzi` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `utenti` (`id` int(11) NOT NULL AUTO_INCREMENT, `email` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `ruolo` enum('studente','professore','admin') NOT NULL DEFAULT 'studente', `bannato` tinyint(1) NOT NULL DEFAULT 0, `avatar` varchar(255) DEFAULT NULL, `created_at` timestamp NOT NULL DEFAULT current_timestamp(), PRIMARY KEY (`id`), UNIQUE KEY `email` (`email`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `appunti` (`id` int(11) NOT NULL AUTO_INCREMENT, `titolo` varchar(255) NOT NULL, `file_pdf` varchar(255) NOT NULL, `data_upload` timestamp NOT NULL DEFAULT current_timestamp(), `id_utente` int(11) DEFAULT NULL, `id_materia` int(11) DEFAULT NULL, `anno` varchar(20) DEFAULT NULL, `stato` enum('approvato','in_revisione','rifiutato') NOT NULL DEFAULT 'approvato', PRIMARY KEY (`id`), KEY `id_utente` (`id_utente`), KEY `id_materia` (`id_materia`), KEY `idx_appunti_stato` (`stato`), CONSTRAINT `appunti_ibfk_1` FOREIGN KEY (`id_utente`) REFERENCES `utenti` (`id`), CONSTRAINT `appunti_ibfk_2` FOREIGN KEY (`id_materia`) REFERENCES `materie` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `commenti` (`id` int(11) NOT NULL AUTO_INCREMENT, `testo` text NOT NULL, `data_commento` timestamp NOT NULL DEFAULT current_timestamp(), `id_utente` int(11) DEFAULT NULL, `id_appunto` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `id_utente` (`id_utente`), KEY `id_appunto` (`id_appunto`), CONSTRAINT `commenti_ibfk_1` FOREIGN KEY (`id_utente`) REFERENCES `utenti` (`id`), CONSTRAINT `commenti_ibfk_2` FOREIGN KEY (`id_appunto`) REFERENCES `appunti` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `valutazioni` (`id` int(11) NOT NULL AUTO_INCREMENT, `voto` int(11) DEFAULT NULL CHECK (`voto` between 1 and 5), `id_utente` int(11) DEFAULT NULL, `id_appunto` int(11) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `id_utente` (`id_utente`,`id_appunto`), KEY `id_appunto` (`id_appunto`), CONSTRAINT `valutazioni_ibfk_1` FOREIGN KEY (`id_utente`) REFERENCES `utenti` (`id`), CONSTRAINT `valutazioni_ibfk_2` FOREIGN KEY (`id_appunto`) REFERENCES `appunti` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `messaggi` (`id` int(11) NOT NULL AUTO_INCREMENT, `testo` text NOT NULL, `data_invio` timestamp NOT NULL DEFAULT current_timestamp(), `mittente_id` int(11) DEFAULT NULL, `destinatario_id` int(11) DEFAULT NULL, PRIMARY KEY (`id`), KEY `mittente_id` (`mittente_id`), KEY `destinatario_id` (`destinatario_id`), CONSTRAINT `messaggi_ibfk_1` FOREIGN KEY (`mittente_id`) REFERENCES `utenti` (`id`), CONSTRAINT `messaggi_ibfk_2` FOREIGN KEY (`destinatario_id`) REFERENCES `utenti` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `otp` (`id` int(11) NOT NULL AUTO_INCREMENT, `codice` varchar(6) NOT NULL, `id_utente` int(11) DEFAULT NULL, `scadenza` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`id`), KEY `id_utente` (`id_utente`), CONSTRAINT `otp_ibfk_1` FOREIGN KEY (`id_utente`) REFERENCES `utenti` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE `reset_password` (`id` int(11) NOT NULL AUTO_INCREMENT, `token` varchar(255) NOT NULL, `id_utente` int(11) DEFAULT NULL, `scadenza` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(), PRIMARY KEY (`id`), KEY `id_utente` (`id_utente`), CONSTRAINT `reset_password_ibfk_1` FOREIGN KEY (`id_utente`) REFERENCES `utenti` (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `scuole` (`nome`) VALUES ('ITIS'), ('LICEO');
INSERT INTO `indirizzi` (`nome`, `id_scuola`) VALUES ('Informatica',1),('Meccanica',1),('Elettrotecnica',1),('Liceo Scientifico',2);
INSERT INTO `materie` (`nome`, `id_indirizzo`) VALUES ('Programmazione',1),('Sistemi e Reti',1),('Tecnologie Informatiche',1),('Matematica',1),('Inglese',1),('Meccanica',2),('Disegno Tecnico',2),('Tecnologia Meccanica',2),('Matematica',2),('Fisica',2),('Elettronica',3),('Elettrotecnica',3),('Sistemi Automatici',3),('Matematica',3),('Fisica',3),('Matematica',4),('Fisica',4),('Scienze Naturali',4),('Italiano',4),('Latino',4),('Inglese',4);
COMMIT;
