<?php
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../config/helpers.php';
setHeaders();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') errore('Metodo non consentito.', 405);
$body     = getBody();
$token    = trim($body['token']    ?? '');
$password = trim($body['password'] ?? '');
if (!$token || !$password) errore('Token e nuova password obbligatori.');
if (strlen($password) < 6) errore('La password deve avere almeno 6 caratteri.');
$stmt = $conn->prepare('SELECT id_utente, scadenza FROM reset_password WHERE token = ?');
$stmt->bind_param('s', $token);
$stmt->execute();
$dati = $stmt->get_result()->fetch_assoc();
$stmt->close();
if (!$dati) errore('Token non valido.', 400);
if (strtotime($dati['scadenza']) < time()) errore('Token scaduto. Richiedi un nuovo link.', 400);
$hash = password_hash($password, PASSWORD_BCRYPT);
$stmt = $conn->prepare('UPDATE utenti SET password = ? WHERE id = ?');
$stmt->bind_param('si', $hash, $dati['id_utente']);
$stmt->execute();
$stmt->close();
$conn->prepare('DELETE FROM reset_password WHERE token = ?')->bind_param('s', $token)->execute();
risposta(['messaggio' => 'Password aggiornata con successo.']);
